language: ruby

rvm:
  - "2.3.0"

install:
  - npm install -g karma --save-dev

before_script:
 - npm install -g karma-jasmine@0.1.0 --save-dev
 - npm install -g phantomjs --save-dev
 - npm install -g karma-phantomjs-launcher --save-dev
 - npm install -g karma-coverage --save-dev
 - cd observatorio-server/
 - gem install rspec rspec-rails simplecov
 - bundle install
 - cd ../observatorio-app
 - npm install angular-mocks@1.5.3 --save-dev

script:
  - cd ../observatorio-server/
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec
  - karma start --single-run --browsers PhantomJS ../observatorio-app/karma.conf.js

notifications:
  email:
    recipients:
      - antoniojk7@gmail.com
      - leomeister22@gmail.com
      - lucas.advc@gmail.com
      - skingk.f@gmail.com
      - vitor.nere@hotmail.com

