language: ruby

rvm:
  - "2.3.0"

before_script:
 - gem install rspec rspec-rails simplecov
 - bundle install
 - rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec

notifications:
  email:
    recipients:
      - antoniojk7@gmail.com
      - leomeister22@gmail.com
      - lucas.advc@gmail.com
      - skingk.f@gmail.com
      - vitor.nere@hotmail.com

