language: ruby

rvm:
  - "2.3.1"
  
before_script:
 - cd observatorio-server/
 - gem install rspec rspec-rails simplecov
 - bundle install

script:
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec

notifications:
  email:
    recipients:
      - skingk.f@gmail.com

